name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1be1ab1818acebfa7b8f8c99e8941f2420e5c1b09fa40a12fa4e324c2d57dc3c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
