name = "Avery's Essentials"
author = "averythebird"
version = "1.20.4-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00f4f690b16f400703192f6350d448011edaf8b1da0b1ec2f37d03d37aed1874"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
