name = "Avery's Essentials"
author = "averythebird"
version = "rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e659b087bb6368c2ac6869cf1de665d5855163fa314137987a327866acf1b714"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
