name = "Winter's Tweaks"
author = "Wolfyo"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9b9f6f79a80c8999d22fdf1f95c43455058e1b2f149f8193a552236490c15ee"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
