name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b648205a7f79e556b7eb4f6e560d9ec18a45bb9d510d4cc34ba40b2fb9c347b"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
