name = "Winter's Tweaks"
author = "Wolfyo"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3afd1eb076fd7f80918fd38bcae0f0e1e80004d87c663475f7ce13d18929f760"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
