name = "Avery's Essentials"
author = "averythebird"
version = "1.20.4-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d17e3b6bcb6b2c7843fead1d5df451262e7ea4e95cb0fae9914d243fd990ddd"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2", "1.20.3", "1.20.4"]
