name = "Avery's Essentials"
author = "averythebird"
version = "rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0400be6ac9910248bfee89f842bb329356160fd3fd17d85b20c02243c5e5ce7f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
