name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b5746c4996ca00996991694c34d51a2b86ff579ba12779a0dd1a78a4075b136"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
