name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b586955dd2af1d5de916164a8560f68d244e087f387ba44a01dd8f73198fd00e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
