name = "Avery's Essentials"
author = "averythebird"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65e5335e67b17da4ca76edd02c3c7994d216a26151ac8757448b7cb7010c5399"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
