name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff0cd764408962bd65761eb92b8b53b743a35a2a738b5e1ab069129e02c2eda9"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
