name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc20d3bc344a7c3eab40833275a65d945fa61db871033f6fc9ab1148208508f5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
