name = "Avery's Essentials"
author = "averythebird"
version = "2.0-1.20.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9ffe024089acb0a132902f192d59a0f83bd0eda488df7ada84cfbbcc8b6c7f6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
