name = "Avery's Essentials"
author = "averythebird"
version = "rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f56739857f9d32a43715856430f62cdf193f9a7e8ad96b4f971a3decc8c4d48d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
