name = "Avery's Essentials"
author = "averythebird"
version = "rolling_release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1a75aee8a41841a6c495cec114e3ccca9152f84d4a3eb4a3b5f671d4e69163e"

[versions]
fabric = "0.15.9"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
