name = "Avery's Essentials"
author = "averythebird"
version = "rolling"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6ea4c2e46be1f15bb6c9d2d95985f39114544a4cfdff49014541923a67852a4"

[versions]
fabric = "0.15.7"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.4"]
