name: Push to Main Continuous Deployment

on:
  push:
    branches: [main]
    paths:
      - "config/**"
      - "mods/**"
      - "resourcepacks/**"
      - "index.toml"
      - "pack.toml"

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          #
          fetch-depth: 50

      - name: Determine Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "rolling-${major}.${minor}.${patch}"

      - name: Export
        run: |
          docker run --rm -v $(pwd):/workspace dalbitresb12/packwiz modrinth export

      - name: Deploy
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: xNGaA9W4
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: any
          name: ${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
          files: "*.mrpack"
          loaders: fabric
          game-versions: ${{ vars.MC_VERSION }}
