name: Push To Main Continuous Deployment

on:
  push:
    branches: [main]
    paths:
      - "config/**"
      - "mods/**"
      - "resourcepacks/**"
      - "index.toml"
      - "pack.toml"

jobs:
  export_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_STATE

      - name: Export
        run: |
          docker run --rm -v $(pwd):/workspace dalbitresb12/packwiz modrinth export --output "averys-essentials-${{ steps.version.outputs.date }}.mrpack"

      - name: Deploy
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: xNGaA9W4
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-unfeature-mode: any
          name: ${{ steps.version.outputs.date }}
          version: ${{ steps.version.outputs.date }}
          files: "*.mrpack"
          loaders: fabric
          game-versions: ${{ vars.MC_VERSION }}
