name: Pull Request Continuous Integration

on:
  pull_request:
    branches: [main]
    paths:
      - "packwiz/**"

jobs:
  export:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packwiz

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export
        run: |
          docker run --rm -v $(pwd):/workspace dalbitresb12/packwiz modrinth export
